spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: spdlqj21tp@gmail.com
    password: ruddnr6340!
    properties:
      mail:
        smtp:
          auth: true
          staartls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3308/mypart
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: C:/Users/Lee Kyoung Wook/Desktop/java/springIMG
mybatis:
  mapper-locations: mybatis-mapper/*.xml
  type-aliases-package: com.koreait.socket

#톰캣 포트 변경
server:
  port: 8090